name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: 🧪 Run app and test HTTP response
        run: |
          pip install -r requirements.txt
          python app.py &
          sleep 3
          curl --fail http://127.0.0.1:5000/ || (echo "App failed to respond!" && exit 1)

      - name: 📦 Audit dependencies with pip-audit
        run: |
          pip install pip-audit
          pip-audit

      - name: Build Docker image
        run: docker build -t my-secure-app:latest .
      - name: Run Semgrep scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/ci"